/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* src = "c.sv:1" *)
module adder_a(a, b, cin, sum, cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  (* src = "c.sv:1" *)
  input a;
  (* src = "c.sv:1" *)
  input b;
  (* src = "c.sv:1" *)
  input cin;
  (* src = "c.sv:1" *)
  output cout;
  (* src = "c.sv:1" *)
  output sum;
  NOR _10_ (
    .A(b),
    .B(_01_),
    .Y(_05_)
  );
  NOR _11_ (
    .A(_03_),
    .B(_05_),
    .Y(sum)
  );
  NAND _12_ (
    .A(_09_),
    .B(_04_),
    .Y(cout)
  );
  NOT _13_ (
    .A(b),
    .Y(_06_)
  );
  NOR _14_ (
    .A(cin),
    .B(a),
    .Y(_07_)
  );
  NOT _15_ (
    .A(_07_),
    .Y(_08_)
  );
  NAND _16_ (
    .A(cin),
    .B(a),
    .Y(_09_)
  );
  NOT _17_ (
    .A(_09_),
    .Y(_00_)
  );
  NOR _18_ (
    .A(_07_),
    .B(_00_),
    .Y(_01_)
  );
  NAND _19_ (
    .A(_08_),
    .B(_09_),
    .Y(_02_)
  );
  NOR _20_ (
    .A(_06_),
    .B(_02_),
    .Y(_03_)
  );
  NAND _21_ (
    .A(b),
    .B(_01_),
    .Y(_04_)
  );
endmodule

(* top =  1  *)
(* src = "c.sv:5" *)
module adder_c(a, b, cin, sum, cout);
  (* src = "c.sv:5" *)
  input [3:0] a;
  (* src = "c.sv:5" *)
  input [3:0] b;
  (* src = "c.sv:6" *)
  wire [4:0] c;
  (* src = "c.sv:5" *)
  input cin;
  (* src = "c.sv:5" *)
  output cout;
  (* src = "c.sv:5" *)
  output [3:0] sum;
  (* module_not_derived = 32'd1 *)
  (* src = "c.sv:11" *)
  adder_a _0_ (
    .a(a[0]),
    .b(b[0]),
    .cin(cin),
    .cout(c[1]),
    .sum(sum[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "c.sv:11" *)
  adder_a _1_ (
    .a(a[1]),
    .b(b[1]),
    .cin(c[1]),
    .cout(c[2]),
    .sum(sum[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "c.sv:11" *)
  adder_a _2_ (
    .a(a[2]),
    .b(b[2]),
    .cin(c[2]),
    .cout(c[3]),
    .sum(sum[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "c.sv:11" *)
  adder_a _3_ (
    .a(a[3]),
    .b(b[3]),
    .cin(c[3]),
    .cout(cout),
    .sum(sum[3])
  );
  assign { c[4], c[0] } = { cout, cin };
endmodule
