/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module complement_2_sy(a, w);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  input [7:0] a;
  wire [8:0] carry;
  output [7:0] w;
  NOT _24_ (
    .A(_14_),
    .Y(_22_)
  );
  NOT _25_ (
    .A(_15_),
    .Y(_23_)
  );
  NOT _26_ (
    .A(_08_),
    .Y(_16_)
  );
  NOT _27_ (
    .A(_09_),
    .Y(_17_)
  );
  NOT _28_ (
    .A(_10_),
    .Y(_18_)
  );
  NOT _29_ (
    .A(_11_),
    .Y(_19_)
  );
  NOT _30_ (
    .A(_12_),
    .Y(_20_)
  );
  NOT _31_ (
    .A(_13_),
    .Y(_21_)
  );
  half_adder _32_ (
    .a(_00_),
    .cin(1'h1),
    .cout(carry[1]),
    .s(w[0])
  );
  half_adder _33_ (
    .a(_01_),
    .cin(carry[1]),
    .cout(carry[2]),
    .s(w[1])
  );
  half_adder _34_ (
    .a(_02_),
    .cin(carry[2]),
    .cout(carry[3]),
    .s(w[2])
  );
  half_adder _35_ (
    .a(_03_),
    .cin(carry[3]),
    .cout(carry[4]),
    .s(w[3])
  );
  half_adder _36_ (
    .a(_04_),
    .cin(carry[4]),
    .cout(carry[5]),
    .s(w[4])
  );
  half_adder _37_ (
    .a(_05_),
    .cin(carry[5]),
    .cout(carry[6]),
    .s(w[5])
  );
  half_adder _38_ (
    .a(_06_),
    .cin(carry[6]),
    .cout(carry[7]),
    .s(w[6])
  );
  half_adder _39_ (
    .a(_07_),
    .cin(carry[7]),
    .cout(carry[8]),
    .s(w[7])
  );
  assign carry[0] = 1'h1;
  assign _14_ = a[6];
  assign _06_ = _22_;
  assign _15_ = a[7];
  assign _07_ = _23_;
  assign _08_ = a[0];
  assign _00_ = _16_;
  assign _09_ = a[1];
  assign _01_ = _17_;
  assign _10_ = a[2];
  assign _02_ = _18_;
  assign _11_ = a[3];
  assign _03_ = _19_;
  assign _12_ = a[4];
  assign _04_ = _20_;
  assign _13_ = a[5];
  assign _05_ = _21_;
endmodule

module half_adder(a, cin, s, cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  input a;
  input cin;
  output cout;
  output s;
  NOT _07_ (
    .A(_01_),
    .Y(_03_)
  );
  NOT _08_ (
    .A(_00_),
    .Y(_04_)
  );
  NOR _09_ (
    .A(_03_),
    .B(_04_),
    .Y(_02_)
  );
  NOR _10_ (
    .A(_01_),
    .B(_00_),
    .Y(_05_)
  );
  NOR _11_ (
    .A(_02_),
    .B(_05_),
    .Y(_06_)
  );
  assign _01_ = cin;
  assign _00_ = a;
  assign cout = _02_;
  assign s = _06_;
endmodule
